<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./ship-small-ghost-transformed.glb --transform --draco
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/ship-small-ghost-transformed-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['ship-small-ghost_1'].geometry}
      material={gltf.materials.colormap}
    >
      <T.Mesh
        geometry={gltf.nodes['sail-b'].geometry}
        material={gltf.materials.colormap}
        position={[0, 4.55, -4.01]}
      />
      <T.Mesh
        geometry={gltf.nodes['sail-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 3.14, 0.67]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-b'].geometry}
        material={gltf.materials.colormap}
        position={[0, 8.84, 0.68]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 5.48, 2.97]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-c'].geometry}
        material={gltf.materials.colormap}
        position={[0, 8.24, -4.01]}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
