<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./ship-large.glb --transform --draco
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/ship-large-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['ship-large_1'].geometry}
      material={gltf.materials.colormap}
    >
      <T.Mesh
        geometry={gltf.nodes['sail-b'].geometry}
        material={gltf.materials.colormap}
        position={[0, 4.55, -5.36]}
      />
      <T.Mesh
        geometry={gltf.nodes['sail-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 3.14, -0.36]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-c'].geometry}
        material={gltf.materials.colormap}
        position={[0, 8.24, -5.36]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-b'].geometry}
        material={gltf.materials.colormap}
        position={[0, 8.84, -0.34]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 5.68, 4.22]}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
