<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./ship-cargo-b.glb --transform --draco
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/ship-cargo-b-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['ship-cargo-b_1'].geometry}
      material={gltf.materials.colormap}
    >
      <T.Mesh
        geometry={gltf.nodes['cargo-a'].geometry}
        material={gltf.materials.colormap}
        position={[-0.01, 1.1, -0.11]}
      />
      <T.Mesh
        geometry={gltf.nodes['cargo-b'].geometry}
        material={gltf.materials.colormap}
        position={[0.12, 1.1, -2.97]}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
