<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./cannon-mobile.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/cannon-mobile-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['cannon-mobile_1'].geometry}
      material={gltf.materials.colormap}
    >
      <T.Mesh
        geometry={gltf.nodes.Group.geometry}
        material={gltf.materials.colormap}
        position={[-0.23, 0.63, -0.83]}
        rotation={[0, 0, 0.26]}
      />
      <T.Mesh
        geometry={gltf.nodes.Group_1.geometry}
        material={gltf.materials.colormap}
        position={[0.52, 0.55, -0.83]}
        rotation={[0, 0, -0.26]}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
