<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./chest.glb --transform
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('/chest-transformed.glb')

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="chest">
      <T.Mesh
        name="chest_1"
        geometry={gltf.nodes.chest_1.geometry}
        material={gltf.materials.colormap}
      >
        <T.Mesh
          name="lid"
          geometry={gltf.nodes.lid.geometry}
          material={gltf.materials.colormap}
          position={[0, 0.51, -0.51]}
        />
      </T.Mesh>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
