<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./ship-wreck.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/ship-wreck-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['ship-wreck_1'].geometry}
      material={gltf.materials.colormap}
    >
      <T.Mesh
        geometry={gltf.nodes.grass.geometry}
        material={gltf.materials.colormap}
        position={[-1.46, 2.1, 0.89]}
        rotation={[0, 1.12, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_1.geometry}
        material={gltf.materials.colormap}
        position={[1.13, 2.1, -1.54]}
        rotation={[-Math.PI, 0.12, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_2.geometry}
        material={gltf.materials.colormap}
        position={[-0.39, 2.23, 2.37]}
        rotation={[-Math.PI, 0.47, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_3.geometry}
        material={gltf.materials.colormap}
        position={[-0.92, 2.23, 1.84]}
        rotation={[-Math.PI, 1.42, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_4.geometry}
        material={gltf.materials.colormap}
        position={[-0.4, 3.63, -4.51]}
        rotation={[Math.PI, -1.45, Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_5.geometry}
        material={gltf.materials.colormap}
        position={[0.99, 3.5, -4.2]}
        rotation={[Math.PI, -0.64, Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_6.geometry}
        material={gltf.materials.colormap}
        position={[-0.24, 1.6, -0.98]}
        rotation={[0, 1.12, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_7.geometry}
        material={gltf.materials.colormap}
        position={[1.93, 2.1, -0.59]}
        rotation={[0, -1.39, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.grass_8.geometry}
        material={gltf.materials.colormap}
        position={[1.66, 2.6, 1.69]}
        rotation={[-Math.PI, 0.14, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.Group.geometry}
        material={gltf.materials.colormap}
        position={[0.79, 4.67, -5]}
      />
      <T.Mesh
        geometry={gltf.nodes['sail-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 3.14, 0.67]}
      />
      <T.Mesh
        geometry={gltf.nodes.Group_1.geometry}
        material={gltf.materials.colormap}
        position={[-0.16, 3.5, -3.84]}
      />
      <T.Mesh
        geometry={gltf.nodes.Group_2.geometry}
        material={gltf.materials.colormap}
        position={[-0.53, 2.1, 1.96]}
      />
      <T.Mesh
        geometry={gltf.nodes.Group_3.geometry}
        material={gltf.materials.colormap}
        position={[-0.7, 2.1, 0.9]}
      />
      <T.Mesh
        geometry={gltf.nodes.Group_4.geometry}
        material={gltf.materials.colormap}
        position={[-1.17, 3.5, -4.21]}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
