<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./ship-pirate-small.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/ship-pirate-small-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['ship-pirate-small_1'].geometry}
      material={gltf.materials.colormap}
    >
      <T.Mesh
        geometry={gltf.nodes['sail-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 3.14, -0.63]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-b'].geometry}
        material={gltf.materials.colormap}
        position={[0, 8.84, -0.62]}
      />
      <T.Mesh
        geometry={gltf.nodes['flag-a'].geometry}
        material={gltf.materials.colormap}
        position={[0, 5.48, 2.27]}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
