<!--
	Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
	Command: npx @threlte/gltf@3.0.0 boat-fishing-small.glb
  -->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import scaleObject from '$lib/ModelScaler';
  import { Mesh } from 'three';
  import Bbox from '$lib/bbox'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/boat-fishing-small.glb')
  const bbox = Bbox.computeSize(gltf.nodes['boat-fishing-small_1'].geometry);
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
  >
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['boat-fishing-small_1'].geometry}
      material={gltf.materials.colormap}
      position={[ 0, 0, 0 ]}
      />
	{:catch err}
      {@render error?.({ error: err })}
	{/await}

{@render children?.({ ref })}
</T.Group>
